.travis.yml
Package postgresql directory
Check the releases
Package postgresql directory
**- Referenced issues**
=> [bugfix] package postgresql directory to the released package

node/PostgreSqlDbClient.js
enable logging
drain pool if an error is occurred
After a connection timeout the pool is drained
Error handling
=> [bugfix] error handling

README.md
Add supported databses to the README file
Add supported databses to the README file
=> [doc] extends readme with supported databases

.travis.yml
=> [bugfix] fix included directory name

db/DbPreferences.js
rename the below DB preferences:
- Database Schema -> Table Schema
- Database -> Table Catalog
=> [bugfix] rename DB preferences

db/DbManager.js
fix connection close function
fix connection close function
=> [bugfix] fix connection close function

db/DbAnalyzer.js, mssql/MsSqlAnalyzer.js, mysql/MySqlAnalyzer.js, postgresql/PostgreSqlAnalyzer.js
refactor: processing results
refactor: processing results
=> [refactor] process results

README.md
=> [ci] postgres

.travis.yml, README.md, __tests__.skip/ApplicationTest.js, mssql/MsSqlDbClient.js, mysql/MySqlDbClient.js, package-lock.json, package.json, postgresql/PostgreSqlDbClient.js
=> [test] application

README.md
=> [test] code coverage

.travis.yml
=> [bugfix] fix CI issue, github token

mssql/MsSqlAnalyzer.js, package-lock.json, package.json
Deep merge in case of MS SQL config
Wrong merging in case of nested objects
Deep merge in case of MS SQL config
=> [bugfix] MS SQL config properties - deep merge

.snyk, .travis.yml, __tests__/db/MySqlManager.js, __tests__/db/PostgreSqlManager.js
=> [bugfix][travis-ci] remove mysql upgrade

test/mysql/docker-compose.yml
=> [test] use MySQL 8.0

.github/workflows/github-actions-ci.yml, .github/workflows/github-actions-release.yml, mssql/MsSqlDbClient.js, package-lock.json, package.json, postgresql/PostgreSqlDbClient.js, test/mssql/docker-compose.yml
Replace TravisCI with GitHub Actions
=> [github-actions] replace TravisCI with GitHub Actions

.github/workflows/github-actions-ci.yml
=> [bugfix] fix CI

.github/workflows/github-actions-ci.yml, __tests__/db/MsSqlManager.js, db/DbPreferences.js, mssql/MsSqlDbClient.js, mssql/MsSqlManager.js, package-lock.json, package.json, preferences/mssql.json, test/mssql/docker-compose.yml
Replace tedious with node-mssql
Change the DbClient class
Run integration tests
Replace tedious with node-mssql
=> Replace tedious with node mssql

package-lock.json, package.json
=> [dep] remove "lodash" dependency

.github/workflows/codeql-analysis.yml, README.md, __tests__/db/MySqlManager.js, __tests__/db/PostgreSqlManager.js
Fix the incomplete regular expression for hostnames
Escape '.' before 'example.org', so it does not match more hosts than expected.
Automated tests
Fix the incomplete regular expression for hostnames
=> [fix] Incomplete regular expression for hostnames

.github/workflows/github-actions-ci.yml, .github/workflows/github-actions-release.yml
=> [workflow] update actions

.github/workflows/github-actions-ci.yml, __tests__/db/MsSqlManager.js
=> [workflow] set NodeJS version to 16

package-lock.json, package.json
=> [package.json] remove snyk. it is part of the CI workflow

package-lock.json, package.json
=> [package.json] remove coveralls dep. it is aprt of the CI workflow

.github/workflows/github-actions-release.yml
=> [workflow] set-output command is deprecated

.github/workflows/github-actions-release.yml
=> [workflow] replace create-release and upload-release-asset actions

__tests__/db/MsSqlManager.js, db/DbPreferences.js, main.js, mssql/MsSqlAnalyzer.js, mssql/MsSqlManager.js, mssql/MsSqlPreferences.js, package-lock.json, package.json, postgresql/PostgreSqlAnalyzer.js, preferences/mssql.json
=> [feature][mssql] support domain login

package-lock.json, package.json
=> [deps] bump mysql2
